name: Diting ReSukiSU IPv6 NAT off test
on:
  workflow_dispatch:
  push:
    branches: [diting-ipv6-nat-off]
    paths: [.github/workflows/diting-test.yml]
permissions:
  contents: write
  actions: write
jobs:
  nomount:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - id: module
        uses: ./.github/actions/nomount-metamodule
        with:
          commit: d0f57d5c37ff02aae2299daded57919153240cb3
      - uses: actions/upload-artifact@v7
        with:
          name: NoMount-Metamodule
          path: ${{ steps.module.outputs.module_dir }}/**
          if-no-files-found: error
  kernel:
    needs: nomount
    uses: ./.github/workflows/build.yml
    with:
      version: android12-5.10
      android_version: android12
      kernel_version: '5.10'
      sublevel: '136'
      os_patch_level: '2022-11'
      variant: ReSukiSU-NAToff-TEST
      feature_set: 'SUSFS,NoMount,BBG,NET,DS,NTSync,Ptrace,Unicode,BTF'
      root_flavor: resukisu
      root_commit: 3c1882886dbbb54f4aae7ddf205f8ccde32c2a34
      susfs_commit: ec785f47d49f7b3871ca9356f450411020af7017
      nomount_commit: d0f57d5c37ff02aae2299daded57919153240cb3
      kernel_patches_commit: 757201d983e2549dc7945a21fa6a056eb2e55263
      anykernel3_commit: e1e9dce98430c5c6f231f7094a8c7f4ecaf50948
      droidspaces_commit: f60294ac4c8aa2cc860773ac85bc5790104eb77f
      brand_name: DitingTest
      bypass: false
      use_cache: false
